// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmDh-mlpYOVcJptQoZVe71tjmUJezK2NE',
    appId: '1:481506527728:web:8c7e09b2389157398f7535',
    messagingSenderId: '481506527728',
    projectId: 'multi-store-690ed',
    authDomain: 'multi-store-690ed.firebaseapp.com',
    storageBucket: 'multi-store-690ed.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3W8oZtjCY7Ha-RozeNTJSSDG3-_nLiUg',
    appId: '1:481506527728:android:4e1c26ef915ba9248f7535',
    messagingSenderId: '481506527728',
    projectId: 'multi-store-690ed',
    storageBucket: 'multi-store-690ed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjSjLwF9rDEDoayLFYyIyUE5to-XnX1aI',
    appId: '1:481506527728:ios:8361e893c274b08d8f7535',
    messagingSenderId: '481506527728',
    projectId: 'multi-store-690ed',
    storageBucket: 'multi-store-690ed.appspot.com',
    iosBundleId: 'com.example.multiStoreAppWithFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjSjLwF9rDEDoayLFYyIyUE5to-XnX1aI',
    appId: '1:481506527728:ios:94361982871236c08f7535',
    messagingSenderId: '481506527728',
    projectId: 'multi-store-690ed',
    storageBucket: 'multi-store-690ed.appspot.com',
    iosBundleId: 'com.example.multiStoreAppWithFirebase.RunnerTests',
  );
}
